### ISSUE TITLE
ZeroDivisionError in frontend.py

### ISSUE THREAD

**Issue by ghost** [avanc/mopidy-headless#1]
I wanted use this with a rotary encoder.  The "official" mopidy-headless via pip3 doesn't work either as it been modded for a keypad so won't read an encoder at all.
Ic config.txt I have: dtoverlay=rotary-encoder,pin_a=5,pin_b=6,relative_axis=1,steps-per-period=2 and this works with another python app I am working on.
Here's the error message.

ERROR    2022-06-11 12:17:59,256 [2364:InputFrontend-7] pykka
Unhandled exception in InputFrontend (urn:uuid:b9f117c3-e68a-461b-ba74-53f02da48141):
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
self.on_start()
File "/usr/local/lib/python3.7/dist-packages/mopidy_headless/frontend.py", line 66, in on_start
self.change_playlist(0)
File "/usr/local/lib/python3.7/dist-packages/mopidy_headless/frontend.py", line 100, in change_playlist
self.selected_playlist= (self.selected_playlist+value) % len(self.playlists)
ZeroDivisionError: integer division or modulo by zero

**Comment by qurben** [comment]
`mopidy-headless` on PyPi is my fork at [qurben/mopidy-headless](https://qurben/mopidy-headless).

I think this repo doesn't support Mopidy 3 yet, what version of Mopidy are you using?

**Comment by ghost** [comment]
Hello Qurben
I installed whatever the latest version provided through apt on raspbian. I forget now as I started again with just mpd and wrote (actually still writing) my own internet radio player. The encoder is a device in /dev/input/by-path/platform-rotary@6-event
I'm going to close this as I've abandoned mopidy and it looks like this repo is pretty much abandoned too.
